USE [PHARMASTORE]
GO

/****** Object:  Table [dbo].[BuyOrder]    Script Date: 3/27/2018 2:23:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BuyOrder](
	[oid] [int] IDENTITY(1,1) NOT NULL,
	[pid] [int] NOT NULL,
	[cid] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[oid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BuyOrder]  WITH CHECK ADD FOREIGN KEY([cid])
REFERENCES [dbo].[Client] ([cid])
GO

ALTER TABLE [dbo].[BuyOrder]  WITH CHECK ADD FOREIGN KEY([pid])
REFERENCES [dbo].[Product] ([pid])
GO


